### ISSUE TITLE
Centos 6

### ISSUE THREAD

**Issue by mountdevhands** [LTD-Beget/tcpsecrets#2]
При сборке на Centos 6 получаю:
`make -C /lib/modules/2.6.32-642.4.2.el6.x86_64/build M=/usr/src/tcpsecrets modules
make[1]: Entering directory /usr/src/kernels/2.6.32-642.4.2.el6.x86_64'
  CC [M]  /usr/src/tcpsecrets/tcpsecrets.o
In file included from /usr/src/tcpsecrets/tcpsecrets.c:10:
/usr/src/tcpsecrets/system_map.inc:2:1: warning: "SYNCOOKIE_SECRET_ADDR" redefined
/usr/src/tcpsecrets/system_map.inc:1:1: warning: this is the location of the previous definition
/usr/src/tcpsecrets/system_map.inc:3:1: warning: "SYNCOOKIE_SECRET_ADDR" redefined
/usr/src/tcpsecrets/system_map.inc:2:1: warning: this is the location of the previous definition
/usr/src/tcpsecrets/system_map.inc:4:1: warning: "SYNCOOKIE_SECRET_ADDR" redefined
/usr/src/tcpsecrets/system_map.inc:3:1: warning: this is the location of the previous definition
/usr/src/tcpsecrets/tcpsecrets.c:103: warning: initialization from incompatible pointer type
/usr/src/tcpsecrets/tcpsecrets.c:104: error: ‘FTRACE_OPS_FL_SAVE_REGS’ undeclared here (not in a function)
/usr/src/tcpsecrets/tcpsecrets.c: In function ‘fix_cookie_v4_check’:
/usr/src/tcpsecrets/tcpsecrets.c:110: error: implicit declaration of function ‘ftrace_set_filter_ip’
make[2]: *** [/usr/src/tcpsecrets/tcpsecrets.o] Error 1
make[1]: *** [_module_/usr/src/tcpsecrets] Error 2
make[1]: Leaving directory /usr/src/kernels/2.6.32-642.4.2.el6.x86_64'
make: *** [default] Error 2`

Для этих ядер вообще нереально собрать? Для Centos 7 получалось.

**Comment by polachok** [comment]
К сожалению, нужная функциональность FTRACE была добавлена в более поздних ядрах.

**Comment by mountdevhands** [comment]
Верно понимаю, что в этом случае использовать syncookied никак не выйдет для систем с Centos 6 из-за отсутствия этого модуля?

**Comment by polachok** [comment]
К сожалению, на данный момент это так.
Дело в том, что модуль устанавливает обертку для функции cooki_v4_check(), которая заставляет ядро думать, что с данного сокета недавно была отправлена SYN cookie. 
Эта функция реализована через FTRACE.

**Comment by mountdevhands** [comment]
Не подскажите, возможно есть другие способы как на одной карте 10Gbps с netmap обрабатывать пакеты, а уже чистые пакеты отсылать уже ядру и дальше проводить например, проксирование на атакуемый сервер, возможно есть готовые решения к netmap или надо только разбираться с netmap и писать что-то свое, к сожалению толковой информации не нашел, только обрывки статей.
Спасибо.

**Comment by polachok** [comment]
Не знаю таких решений с netmap. Можете посмотреть на purifier (https://github.com/medvedv/purifier), он использует dpdk и там реализован режим synproxy, насколько мне известно.
Вариант для конечных серверов - synsanity (https://github.com/github/synsanity), но я не уверен, что он работает для ядер 2.6.
Мы планируем добавить synproxy режим в syncookied в будущем, но сроки пока назвать не могу.
